spring:
  datasource:
    url: jdbc:h2:mem:authdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  h2:
    console:
      enabled: true
app:
  jwt:
    secret: "01234567890123456789012345678901"
    expiration-seconds: 3600
